"""add face enrollment embedding column

Revision ID: 8ae7fea77f9c
Revises: c2d6f5db84c5
Create Date: 2026-08-17 16:03:32.717515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8ae7fea77f9c'
down_revision: Union[str, None] = 'c2d6f5db84c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('face_enrollments', sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=True))
    op.drop_column('face_enrollments', 'embedding_ref')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('face_enrollments', sa.Column('embedding_ref', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('face_enrollments', 'embedding')
    # ### end Alembic commands ###
